### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by genjikowa** [CasperKristiansson/Twitch-Youtube-Auto-Uploader#1]
Hello, how can I get your program to work? Do you have any instructions? Thank you.

**Comment by CasperKristiansson** [comment]
> Hello, how can I get your program to work? Do you have any instructions? Thank you.

Unfortunately, I haven’t made any easy way to implement this on other devices. The only way if you want to get it working is to manually change all the paths to your desirable directory. And add your twitch API key under twitchGetVideo.py in ID. And add a separate credentials login file from YouTube data v3.

I will in the future add a more automated way / easy way to implement this on other devices.

**Comment by genjikowa** [comment]
I don't understand much about coding, so I'll wait for you to implement an automatic way to use it. Thank you!

**Comment by CasperKristiansson** [comment]
> I don't understand much about coding, so I'll wait for you to implement an automatic way to use it. Thank you!

there we go, I have now uploaded a detailed description on how to implement the code

**Comment by omsenjalia** [comment]
om@localhost:~/twitch03$ python twitchGetVideo.py 
Traceback (most recent call last):
  File "twitchGetVideo.py", line 106, in <module>
    save_data(DATA)
  File "twitchGetVideo.py", line 43, in save_data
    for link in data['clips']:
KeyError: 'clips'
om@localhost:~/twitch03$
om@localhost:~/twitch03$

**Comment by CasperKristiansson** [comment]
> om@localhost:~/twitch03$ python twitchGetVideo.py Traceback (most recent call last): File "twitchGetVideo.py", line 106, in save_data(DATA) File "twitchGetVideo.py", line 43, in save_data for link in data['clips']: KeyError: 'clips' om@localhost:~/twitch03$ om@localhost:~/twitch03$

Fixed the issue. Make sure that you have the latest copy of the code.

**Comment by omsenjalia** [comment]
Ty lemme try
